
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://tpisgvfgslhatykewhqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwaXNndmZnc2xoYXR5a2V3aHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDYwNTUsImV4cCI6MjA2NDUyMjA1NX0.lBcN5F6PlOdvlAdOmcdyHEE6PauPmgun7C_k2UZ0goc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
